CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_user_roles_role_id FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE role_permissions (
  role_id BIGINT NOT NULL,
  permission_id BIGINT NOT NULL,
  PRIMARY KEY (role_id, permission_id),
  CONSTRAINT fk_role_permissions_role_id FOREIGN KEY (role_id) REFERENCES roles(id),
  CONSTRAINT fk_role_permissions_permission_id FOREIGN KEY (permission_id) REFERENCES permissions(id)
);

CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id BIGINT,
  action VARCHAR(64) NOT NULL,
  module VARCHAR(64) NOT NULL,
  entity_type VARCHAR(64),
  entity_id BIGINT,
  details_json CLOB,
  ip VARCHAR(64),
  user_agent VARCHAR(256),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_audit_logs_actor_user_id FOREIGN KEY (actor_user_id) REFERENCES users(id)
);

CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);
CREATE INDEX idx_audit_logs_actor_user_id ON audit_logs(actor_user_id);

CREATE TABLE schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_user_id BIGINT NOT NULL,
  schedule_date DATE NOT NULL,
  time_period VARCHAR(16) NOT NULL,
  fee_cents BIGINT NOT NULL,
  capacity_total INT NOT NULL,
  capacity_remaining INT NOT NULL,
  status VARCHAR(16) NOT NULL,
  version BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_schedules_doctor_user_id FOREIGN KEY (doctor_user_id) REFERENCES users(id)
);

CREATE INDEX idx_schedules_date_period ON schedules(schedule_date, time_period);
CREATE INDEX idx_schedules_doctor ON schedules(doctor_user_id);

CREATE TABLE registration_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serial_no VARCHAR(64) NOT NULL UNIQUE,
  patient_user_id BIGINT NOT NULL,
  schedule_id BIGINT NOT NULL,
  channel VARCHAR(32) NOT NULL,
  status VARCHAR(16) NOT NULL,
  fee_cents BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_registration_orders_patient_user_id FOREIGN KEY (patient_user_id) REFERENCES users(id),
  CONSTRAINT fk_registration_orders_schedule_id FOREIGN KEY (schedule_id) REFERENCES schedules(id)
);

CREATE INDEX idx_registration_orders_patient ON registration_orders(patient_user_id);
CREATE INDEX idx_registration_orders_schedule ON registration_orders(schedule_id);

CREATE TABLE visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registration_order_id BIGINT NOT NULL UNIQUE,
  doctor_user_id BIGINT NOT NULL,
  patient_user_id BIGINT NOT NULL,
  status VARCHAR(16) NOT NULL,
  started_at TIMESTAMP WITH TIME ZONE,
  ended_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_visits_registration_order_id FOREIGN KEY (registration_order_id) REFERENCES registration_orders(id),
  CONSTRAINT fk_visits_doctor_user_id FOREIGN KEY (doctor_user_id) REFERENCES users(id),
  CONSTRAINT fk_visits_patient_user_id FOREIGN KEY (patient_user_id) REFERENCES users(id)
);

CREATE INDEX idx_visits_doctor ON visits(doctor_user_id);
CREATE INDEX idx_visits_patient ON visits(patient_user_id);

CREATE TABLE emrs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_id BIGINT NOT NULL UNIQUE,
  chief_complaint CLOB,
  history_present_illness CLOB,
  physical_exam CLOB,
  diagnosis CLOB,
  treatment_plan CLOB,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_emrs_visit_id FOREIGN KEY (visit_id) REFERENCES visits(id)
);

CREATE TABLE drugs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  spec VARCHAR(128),
  unit VARCHAR(32),
  price_cents BIGINT NOT NULL,
  enabled BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE inventories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drug_id BIGINT NOT NULL UNIQUE,
  quantity INT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_inventories_drug_id FOREIGN KEY (drug_id) REFERENCES drugs(id)
);

CREATE TABLE prescriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_id BIGINT NOT NULL UNIQUE,
  status VARCHAR(16) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_prescriptions_visit_id FOREIGN KEY (visit_id) REFERENCES visits(id)
);

CREATE TABLE prescription_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prescription_id BIGINT NOT NULL,
  drug_id BIGINT NOT NULL,
  quantity INT NOT NULL,
  dosage VARCHAR(64),
  frequency VARCHAR(64),
  days INT,
  unit_price_cents BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_prescription_items_prescription_id FOREIGN KEY (prescription_id) REFERENCES prescriptions(id),
  CONSTRAINT fk_prescription_items_drug_id FOREIGN KEY (drug_id) REFERENCES drugs(id)
);

CREATE INDEX idx_prescription_items_prescription_id ON prescription_items(prescription_id);

CREATE TABLE dispense_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prescription_id BIGINT NOT NULL,
  pharmacist_user_id BIGINT NOT NULL,
  status VARCHAR(16) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_dispense_records_prescription_id FOREIGN KEY (prescription_id) REFERENCES prescriptions(id),
  CONSTRAINT fk_dispense_records_pharmacist_user_id FOREIGN KEY (pharmacist_user_id) REFERENCES users(id)
);

CREATE INDEX idx_dispense_records_prescription_id ON dispense_records(prescription_id);

CREATE TABLE bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serial_no VARCHAR(64) NOT NULL UNIQUE,
  patient_user_id BIGINT NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  source_id BIGINT NOT NULL,
  amount_total_cents BIGINT NOT NULL,
  status VARCHAR(16) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_bills_patient_user_id FOREIGN KEY (patient_user_id) REFERENCES users(id)
);

CREATE INDEX idx_bills_patient ON bills(patient_user_id);

CREATE TABLE bill_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id BIGINT NOT NULL,
  item_type VARCHAR(32) NOT NULL,
  description VARCHAR(256) NOT NULL,
  quantity INT NOT NULL,
  unit_price_cents BIGINT NOT NULL,
  amount_cents BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_bill_items_bill_id FOREIGN KEY (bill_id) REFERENCES bills(id)
);

CREATE INDEX idx_bill_items_bill_id ON bill_items(bill_id);

