CREATE TABLE patient_blacklists (
  patient_user_id BIGINT PRIMARY KEY,
  no_show_count INT NOT NULL,
  last_no_show_at TIMESTAMP WITH TIME ZONE,
  blacklisted_until TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_patient_blacklists_patient_user_id FOREIGN KEY (patient_user_id) REFERENCES users(id)
);

CREATE TABLE stop_clinic_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id BIGINT NOT NULL,
  doctor_user_id BIGINT NOT NULL,
  reason VARCHAR(256),
  status VARCHAR(16) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_stop_clinic_requests_schedule_id FOREIGN KEY (schedule_id) REFERENCES schedules(id),
  CONSTRAINT fk_stop_clinic_requests_doctor_user_id FOREIGN KEY (doctor_user_id) REFERENCES users(id)
);

CREATE INDEX idx_stop_clinic_requests_status ON stop_clinic_requests(status);
CREATE INDEX idx_stop_clinic_requests_schedule_id ON stop_clinic_requests(schedule_id);

