CREATE TABLE sys_user (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL DEFAULT '123456',
  real_name VARCHAR(50) NOT NULL,
  phone VARCHAR(20),
  id_card VARCHAR(18),
  role VARCHAR(20) NOT NULL DEFAULT 'PATIENT',
  avatar VARCHAR(255),
  status INT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sys_user_role ON sys_user(role);
CREATE INDEX idx_sys_user_real_name ON sys_user(real_name);

CREATE TABLE sys_department (
  dept_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dept_name VARCHAR(50) NOT NULL,
  dept_code VARCHAR(20),
  parent_id INT NOT NULL DEFAULT 0,
  dept_desc VARCHAR(255),
  sort_num INT NOT NULL DEFAULT 0,
  status INT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sys_department_parent_id ON sys_department(parent_id);
CREATE INDEX idx_sys_department_status ON sys_department(status);

CREATE TABLE patient_info (
  patient_id BIGINT PRIMARY KEY,
  gender VARCHAR(10),
  age INT,
  address VARCHAR(255),
  emergency_contact VARCHAR(50),
  emergency_phone VARCHAR(20),
  is_special INT NOT NULL DEFAULT 0,
  special_type VARCHAR(50),
  CONSTRAINT fk_patient_info_user FOREIGN KEY (patient_id) REFERENCES sys_user(user_id) ON DELETE CASCADE
);

CREATE TABLE doctor_info (
  doctor_id BIGINT PRIMARY KEY,
  dept_id INT NOT NULL,
  title VARCHAR(50),
  specialty VARCHAR(255),
  consultation_fee DECIMAL(10, 2) NOT NULL DEFAULT 0,
  expert_fee DECIMAL(10, 2),
  CONSTRAINT fk_doctor_info_user FOREIGN KEY (doctor_id) REFERENCES sys_user(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_doctor_info_department FOREIGN KEY (dept_id) REFERENCES sys_department(dept_id)
);

CREATE INDEX idx_doctor_info_dept_id ON doctor_info(dept_id);

CREATE TABLE schedule (
  schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id BIGINT NOT NULL,
  dept_id INT NOT NULL,
  schedule_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  time_slot_duration INT NOT NULL DEFAULT 60,
  total_slots INT NOT NULL DEFAULT 8,
  slots_per_time INT NOT NULL DEFAULT 5,
  registration_fee DECIMAL(10, 2) NOT NULL DEFAULT 0,
  appointment_cycle INT NOT NULL DEFAULT 7,
  status INT NOT NULL DEFAULT 1,
  create_by BIGINT,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_schedule_doctor FOREIGN KEY (doctor_id) REFERENCES doctor_info(doctor_id),
  CONSTRAINT fk_schedule_department FOREIGN KEY (dept_id) REFERENCES sys_department(dept_id)
);

CREATE INDEX idx_schedule_doctor_id ON schedule(doctor_id);
CREATE INDEX idx_schedule_dept_date ON schedule(dept_id, schedule_date);
CREATE INDEX idx_schedule_date ON schedule(schedule_date);

CREATE TABLE number_source (
  source_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id BIGINT NOT NULL,
  slot_number INT NOT NULL,
  slot_start_time TIME NOT NULL,
  slot_end_time TIME NOT NULL,
  total_count INT NOT NULL DEFAULT 0,
  remaining_count INT NOT NULL DEFAULT 0,
  locked_count INT NOT NULL DEFAULT 0,
  status INT NOT NULL DEFAULT 1,
  release_time TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_number_source_schedule FOREIGN KEY (schedule_id) REFERENCES schedule(schedule_id) ON DELETE CASCADE
);

CREATE INDEX idx_number_source_schedule_id ON number_source(schedule_id);
CREATE INDEX idx_number_source_status ON number_source(status);

CREATE TABLE registration_order (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serial_no VARCHAR(30) NOT NULL UNIQUE,
  patient_id BIGINT NOT NULL,
  source_id BIGINT NOT NULL,
  schedule_id BIGINT NOT NULL,
  doctor_id BIGINT NOT NULL,
  dept_id INT NOT NULL,
  order_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lock_expire_time TIMESTAMP NOT NULL,
  pay_time TIMESTAMP,
  pay_method VARCHAR(20),
  pay_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
  order_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  cancel_time TIMESTAMP,
  cancel_reason VARCHAR(255),
  create_channel VARCHAR(20) DEFAULT 'WEB',
  visit_date DATE,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_registration_order_patient FOREIGN KEY (patient_id) REFERENCES patient_info(patient_id),
  CONSTRAINT fk_registration_order_source FOREIGN KEY (source_id) REFERENCES number_source(source_id),
  CONSTRAINT fk_registration_order_schedule FOREIGN KEY (schedule_id) REFERENCES schedule(schedule_id),
  CONSTRAINT fk_registration_order_doctor FOREIGN KEY (doctor_id) REFERENCES doctor_info(doctor_id),
  CONSTRAINT fk_registration_order_department FOREIGN KEY (dept_id) REFERENCES sys_department(dept_id)
);

CREATE INDEX idx_registration_order_patient_id ON registration_order(patient_id);
CREATE INDEX idx_registration_order_source_id ON registration_order(source_id);
CREATE INDEX idx_registration_order_status ON registration_order(order_status);
CREATE INDEX idx_registration_order_lock_expire ON registration_order(order_status, lock_expire_time);
CREATE INDEX idx_registration_order_visit_date ON registration_order(visit_date, order_status);

CREATE TABLE blacklist (
  black_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL UNIQUE,
  missed_count INT NOT NULL DEFAULT 0,
  is_limited INT NOT NULL DEFAULT 0,
  limit_start_time TIMESTAMP,
  limit_end_time TIMESTAMP,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_blacklist_patient FOREIGN KEY (patient_id) REFERENCES patient_info(patient_id) ON DELETE CASCADE
);

CREATE TABLE missed_appointment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  missed_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reason VARCHAR(255),
  CONSTRAINT fk_missed_appointment_patient FOREIGN KEY (patient_id) REFERENCES patient_info(patient_id),
  CONSTRAINT fk_missed_appointment_order FOREIGN KEY (order_id) REFERENCES registration_order(order_id)
);

CREATE INDEX idx_missed_appointment_patient_id ON missed_appointment(patient_id);
CREATE INDEX idx_missed_appointment_order_id ON missed_appointment(order_id);

CREATE TABLE stop_application (
  apply_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id BIGINT NOT NULL,
  schedule_id BIGINT NOT NULL,
  stop_reason VARCHAR(500) NOT NULL,
  proof_url VARCHAR(255),
  apply_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  auditor_id BIGINT,
  audit_time TIMESTAMP,
  audit_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  audit_remark VARCHAR(255),
  CONSTRAINT fk_stop_application_doctor FOREIGN KEY (doctor_id) REFERENCES doctor_info(doctor_id),
  CONSTRAINT fk_stop_application_schedule FOREIGN KEY (schedule_id) REFERENCES schedule(schedule_id)
);

CREATE INDEX idx_stop_application_doctor_id ON stop_application(doctor_id);
CREATE INDEX idx_stop_application_audit_status ON stop_application(audit_status);

CREATE TABLE suspension_application (
  application_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id BIGINT NOT NULL,
  suspension_date DATE NOT NULL,
  reason VARCHAR(500) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  apply_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  audit_time TIMESTAMP,
  auditor_id BIGINT,
  audit_comment VARCHAR(255),
  CONSTRAINT fk_suspension_application_doctor FOREIGN KEY (doctor_id) REFERENCES doctor_info(doctor_id)
);

CREATE INDEX idx_suspension_application_doctor_id ON suspension_application(doctor_id);
CREATE INDEX idx_suspension_application_status ON suspension_application(status);

CREATE TABLE patient (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_no VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(50) NOT NULL,
  gender VARCHAR(10),
  birthday DATE,
  phone VARCHAR(20),
  id_card VARCHAR(18),
  allergy_history CLOB,
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE doctor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_no VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(50) NOT NULL,
  department VARCHAR(100),
  title VARCHAR(50),
  phone VARCHAR(20),
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE medical_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  doctor_id BIGINT NOT NULL,
  chief_complaint CLOB,
  present_illness CLOB,
  physical_exam CLOB,
  diagnosis VARCHAR(500),
  diagnosis_code VARCHAR(50),
  status VARCHAR(20) DEFAULT 'WAITING',
  record_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP,
  CONSTRAINT fk_medical_record_patient FOREIGN KEY (patient_id) REFERENCES patient(id),
  CONSTRAINT fk_medical_record_doctor FOREIGN KEY (doctor_id) REFERENCES doctor(id)
);

CREATE TABLE prescription (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medical_record_id BIGINT,
  patient_id BIGINT NOT NULL,
  doctor_id BIGINT NOT NULL,
  prescription_no VARCHAR(50) NOT NULL UNIQUE,
  drug_name VARCHAR(100) NOT NULL,
  specification VARCHAR(100),
  quantity INT DEFAULT 1,
  usage_desc VARCHAR(200),
  dosage VARCHAR(100),
  duration INT,
  unit_price DECIMAL(10, 2),
  total_amount DECIMAL(10, 2),
  status VARCHAR(20) DEFAULT 'PENDING_AUDIT',
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  audit_time TIMESTAMP,
  audit_result VARCHAR(50),
  reject_reason VARCHAR(500)
);

CREATE INDEX idx_prescription_patient ON prescription(patient_id);
CREATE INDEX idx_prescription_status ON prescription(status);

CREATE TABLE drug_inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drug_code VARCHAR(50) NOT NULL UNIQUE,
  drug_name VARCHAR(100) NOT NULL,
  specification VARCHAR(100),
  manufacturer VARCHAR(200),
  current_stock INT DEFAULT 0,
  min_stock INT DEFAULT 10,
  max_stock INT DEFAULT 1000,
  batch_no VARCHAR(50),
  production_date DATE,
  expiry_date DATE,
  purchase_price DECIMAL(10, 2),
  retail_price DECIMAL(10, 2),
  location VARCHAR(50),
  lock_quantity INT DEFAULT 0
);

CREATE INDEX idx_drug_inventory_name ON drug_inventory(drug_name);

CREATE TABLE charge_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  patient_name VARCHAR(50) NOT NULL,
  charge_no VARCHAR(50) NOT NULL UNIQUE,
  total_amount DECIMAL(10, 2) NOT NULL,
  insurance_amount DECIMAL(10, 2) DEFAULT 0,
  personal_account DECIMAL(10, 2) DEFAULT 0,
  cash_amount DECIMAL(10, 2) DEFAULT 0,
  self_pay DECIMAL(10, 2) DEFAULT 0,
  payment_method VARCHAR(20),
  status VARCHAR(20) DEFAULT 'PENDING_PAYMENT',
  charge_time TIMESTAMP,
  invoice_no VARCHAR(50),
  insurance_serial_no VARCHAR(50),
  remark VARCHAR(500),
  prescription_id BIGINT
);

CREATE INDEX idx_charge_record_patient ON charge_record(patient_id);
CREATE INDEX idx_charge_record_status ON charge_record(status);
CREATE INDEX idx_charge_record_prescription ON charge_record(prescription_id);

CREATE TABLE dispense_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prescription_id BIGINT NOT NULL,
  pharmacist_id BIGINT NOT NULL,
  patient_id BIGINT NOT NULL,
  drug_name VARCHAR(100),
  quantity INT,
  dispense_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) DEFAULT 'DISPENSED'
);

CREATE INDEX idx_dispense_record_prescription ON dispense_record(prescription_id);
CREATE INDEX idx_dispense_record_patient ON dispense_record(patient_id);

CREATE TABLE financial_report (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_date DATE NOT NULL UNIQUE,
  total_income DECIMAL(10, 2) DEFAULT 0,
  cash_amount DECIMAL(10, 2) DEFAULT 0,
  wechat_amount DECIMAL(10, 2) DEFAULT 0,
  alipay_amount DECIMAL(10, 2) DEFAULT 0,
  insurance_amount DECIMAL(10, 2) DEFAULT 0,
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO sys_user (user_id, username, password, real_name, phone, role, status) VALUES
  (1, 'out_admin', '123456', '系统管理员', '13800000001', 'ADMIN', 1),
  (2, 'doctor_zhang', '123456', '张医生', '13800000002', 'DOCTOR', 1),
  (3, 'doctor_li', '123456', '李医生', '13800000003', 'DOCTOR', 1),
  (4, 'patient_liu', '123456', '刘患者', '13900000001', 'PATIENT', 1),
  (5, 'patient_zhao', '123456', '赵患者', '13900000002', 'PATIENT', 1);

INSERT INTO sys_department (dept_id, dept_name, dept_code, parent_id, dept_desc, sort_num, status) VALUES
  (1, '内科', 'IM', 0, '内科门诊', 1, 1),
  (2, '外科', 'SUR', 0, '外科门诊', 2, 1),
  (3, '儿科', 'PED', 0, '儿科门诊', 3, 1);

INSERT INTO patient_info (patient_id, gender, age, address, emergency_contact, emergency_phone, is_special, special_type) VALUES
  (4, '男', 35, '北京市朝阳区', '紧急联系人刘', '13910000001', 0, NULL),
  (5, '女', 28, '北京市海淀区', '紧急联系人赵', '13910000002', 0, NULL);

INSERT INTO doctor_info (doctor_id, dept_id, title, specialty, consultation_fee, expert_fee) VALUES
  (2, 1, '主任医师', '高血压及糖尿病诊治', 15.00, 50.00),
  (3, 2, '主治医师', '普通外科', 20.00, 60.00);

INSERT INTO patient (id, patient_no, name, gender, birthday, phone, allergy_history) VALUES
  (1, 'P1001', '刘患者', '男', DATE '1991-01-15', '13900000001', '青霉素过敏'),
  (2, 'P1002', '赵患者', '女', DATE '1998-06-20', '13900000002', '无');

INSERT INTO doctor (id, doctor_no, name, department, title) VALUES
  (1, 'D001', '医生A', '内科', '主任医师'),
  (2, 'D002', '医生B', '外科', '主治医师');

INSERT INTO drug_inventory (
  drug_code, drug_name, specification, manufacturer, current_stock, min_stock, retail_price, location, expiry_date
) VALUES
  ('D001', '阿莫西林胶囊', '0.5g*20粒', '北方制药', 25, 50, 25.00, 'A-01-01', CURRENT_DATE + 60),
  ('D002', '布洛芬胶囊', '0.3g*24粒', '联合制药', 80, 50, 35.00, 'A-01-02', CURRENT_DATE + 180),
  ('D003', '对乙酰氨基酚片', '0.1g*12片', '白云制药', 60, 50, 45.00, 'A-01-03', CURRENT_DATE + 30);

INSERT INTO medical_record (patient_id, doctor_id, chief_complaint, status) VALUES
  (1, 1, '发热咳嗽', '待接诊'),
  (2, 1, '头痛恶心', '待接诊');

ALTER TABLE sys_user ALTER COLUMN user_id RESTART WITH 6;
ALTER TABLE sys_department ALTER COLUMN dept_id RESTART WITH 4;
ALTER TABLE patient ALTER COLUMN id RESTART WITH 3;
ALTER TABLE doctor ALTER COLUMN id RESTART WITH 3;
ALTER TABLE drug_inventory ALTER COLUMN id RESTART WITH 4;
ALTER TABLE medical_record ALTER COLUMN id RESTART WITH 3;
